name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main   # change if your default branch is different

jobs:
  deploy:
    runs-on: self-hosted   # use your EC2 self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, bcmath, curl
          tools: composer

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run Laravel optimizations
        run: |
          php artisan config:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Set permissions
        run: |
          sudo chown -R www-data:www-data storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache

      - name: Reload PHP-FPM and Nginx
        run: |
          sudo systemctl reload php8.2-fpm
          sudo systemctl reload nginx
